apiVersion: v1
kind: Secret
metadata:
  name: payments-secret
  namespace: fcg
type: Opaque
stringData:
  ConnectionStrings__Default: "Host=payments-db;Port=5432;Database=payments;Username=payments;Password=payments"
  ConnectionStrings__rabbitmq: "amqp://guest:guest@rabbitmq:5672"
  JwtSettings__SecurityKey: "FcgPayments_Secret_Key_2026_High_Security_Token"
